export const namedWods = [
    'Murph',
    'Fran',
    'Cindy',
    'Nick',
    'Chelsea',
    'Angie',
    'Helen',
    'The Seven | The CIA Seven',
    'The Longest Mile',
    'Zeus WOD',
    'The Glen WOD',
    'The Chief WOD',
    'Filthy Fifty Crossfit WOD',
    'Annie',
    'Barbara',
    'Diane',
    'Elizabeth',
    'Frelen',
    'Isabel',
    'Jackie',
    'Karen',
    'Kelly',
    'Linda',
    'Lynne',
    'Mary',
    'Nancy',
    'Nicole',
    'Nate',
    'JT',
    'Nuts',
    'Danny',
    'Roy',
    'Arnie',
    'Luce',
    'Jag 28',
    'Tom',
]