export enum OneRmList {
    Clean = 'Clean',
    Power_Clean = 'Power Clean',
    Clean_and_Jerk = 'Clean and Jerk',
    Hang_Clean = 'Hang Clean',
    Hang_Power_Clean = 'Hang Power Clean',
    Snatch = 'Snatch',
    Power_Snatch = 'Power Snatch',
    Hang_Snatch = 'Hang Snatch',
    Hang_Power_Snatch = 'Hang Power Snatch',
    Push_Jerk = 'Push Jerk',
    Split_Jerk = 'Split Jerk',
    Push_Press = 'Push Press',
    Shoulder_Press = 'Shoulder Press',
    Bench_Press = 'Bench Press',
    Thruster = 'Thruster',
    Back_Squat = 'Back Squat',
    Front_Squat = 'Front Squat',
    Overhead_Squat = 'Overhead Squat',
    Deadlift = 'Deadlift',
}