export const oneRm = [
    'Clean',
    'Power Clean',
    'Clean and jerk',
    'Hang clean',
    'Hang power clean',
    'Snatch',
    'Power Snatch',
    'Hang snatch',
    'Hang power snatch',
    'Muscle snatch',
    'Push jerk',
    'Split jerk',
    'Push press',
    'Shoulder press',
    'Bench press',
    'Thruster',
    'Back squat',
    'Front squat',
    'Overhead squat',
    'Deadlift',
    'Sumo deadlift',
    'Snatch balance 3x1',
    'Turkish get up',
    'Weighted pull-up',
    'Weighted dip',
    'Weighted ring-dip'
]