export enum OneRmList {
    Clean = 'Clean',
    Power_Clean = 'Power Clean',
    Clean_and_jerk = 'Clean and jerk',
    Hang_clean = 'Hang clean',
    Hang_power_clean = 'Hang power clean',
    Snatch = 'Snatch',
    Power_Snatch = 'Power Snatch',
    Hang_snatch = 'Hang snatch',
    Hang_power_snatch = 'Hang power snatch',
    Muscle_snatch = 'Muscle snatch',
    Push_jerk = 'Push jerk',
    Split_jerk = 'Split jerk',
    Push_press = 'Push press',
    Shoulder_press = 'Shoulder press',
    Bench_press = 'Bench press',
    Thruster = 'Thruster',
    Back_squat = 'Back squat',
    Front_squat = 'Front squat',
    Overhead_squat = 'Overhead squat',
    Deadlift = 'Deadlift',
    Sumo_deadlift = 'Sumo deadlift',
    Snatch_balance_3x1 = 'Snatch balance 3x1',
    Turkish_get_up = 'Turkish get up',
    Weighted_pull_up = 'Weighted pull-up',
    Weighted_dip = 'Weighted dip',
    Weighted_ring_dip = 'Weighted ring-dip'
}